### PR TITLE
 Feature: add ability to store eloquent casts as an encrypted string

### PR DESCRIPTION
**Pull request by eugen-stranz**
Similar to Laravel's ability to store [encrypted strings](https://laravel.com/docs/11.x/eloquent-mutators#encrypted-casting) by providing a cast this enhancement allows the storage of data objects / collections as an encrypted string.

It works by appending the ":encrypted" key to the cast within the eloquent model on the specific column

for example:
Screenshot 2024-03-28 at 10 55 53

Screenshot 2024-03-28 at 10 52 07

Both columns "data" and "secrets" store the same data object.
Screenshot 2024-03-28 at 10 53 00

### CODE REVIEW

**Comment by rubenvanassche** [comment]
And some docs so everyone can use this feature!

**Comment by eugen-stranz** [comment]
Hello @rubenvanassche 

I will provide the missing parts this week.

Thank you for your feedback.

**Comment by eugen-stranz** [comment]
Hello @rubenvanassche

the requested tests and documentation have been implemented.

**Comment by rubenvanassche** [comment]
Thanks!

**Pull request merged**
