### PR TITLE
Add support for laravel 11

### PR DESCRIPTION
**Pull request by shuvroroy**

### CODE REVIEW

**Comment by rubenvanassche** [comment]
Looks like the tests are failing

**Comment by shuvroroy** [comment]
@rubenvanassche looks like `inertiajs/inertia-laravel` not supported yet with Laravel 11

**Comment by shuvroroy** [comment]
@rubenvanassche I hope this change will fixed the issue

**Comment by shuvroroy** [comment]
Looks like this PR depends on inertia-laravel package. Will prepare a PR for that one as well today

**Comment by rubenvanassche** [comment]
Looks like laravel-typescript-transformer is still causing problems, do you have some time to PR Laravel 11 over therre?

**Comment by shuvroroy** [comment]
> > Looks like laravel-typescript-transformer is still causing problems, do you have some time to PR Laravel 11 over therre?
> 
> On it 🫡

@rubenvanassche `laravel-typescript-transformer` depends on this [PR](https://github.com/spatie/laravel-model-states/pull/249)

**Pull request merged**
